
# количество рабочих процессов (кол-во cpu)
worker_processes auto;

# Максимум одновременных соединений
events {
    worker_connections 1024;
}

http {
    # MIME
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # формат логов
    # remote_addr - ip адресс
    # remote_user - имя пользователя
    # 192.168.0.1 - admin [дата и время]
    # 192.168.0.1 "GET"
    log_format main '$remote_addr - "$request" [$time_local] $status';

    access_log /var/log/nginx/access.log main; # лог всех запросов
    error_log /var/log/nginx/error.log warn; # лог ошибок

    sendfile on;

    tcp_nopush on; # копит несколько запросов и отправляет
    tcp_nodelay on; # отправляет маленькие запросы сразу

    gzip on; # сжимает и архивирует json
    gzip_types text/plain text/css application/json application/javascript;

    gzip_min_length 1000;

    keepalive_timeout 65; # держим соединение открытым 65 секунд

    client_max_body_size 50M; # максимально можно загружать файлы 50м

    include /etc/nginx/conf.d/*.conf; # import
}


