upstream fastapi_backend{
    server backend:8000;

    keepalive 32;
}

upstream nextjs_frontend{
    server frontend:3000;

    keepalive 32;
}


server {
    listen 80;

    server_name api.malikarakh.uz www.api.malikarakh.uz www.malikarakh.uz malikarakh.uz ;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }


}



server {
    listen 443 ssl;

    server_name api.malikarakh.uz www.api.malikarakh.uz;

    # публичный
    ssl_certificate /etc/letsencrypt/live/malikarakh.uz/fullchain.pem;

    # приватный
    ssl_certificate_key /etc/letsencrypt/live/malikarakh.uz/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_session_cache shared:SSL:10m;

    add_header Strict-Transport-Security "max-age=31536000" always;

    location / {
        proxy_pass http://fastapi_backend;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;

    server_name malikarakh.uz www.malikarakh.uz;

    # публичный
    ssl_certificate /etc/letsencrypt/live/malikarakh.uz/fullchain.pem;

    # приватный
    ssl_certificate_key /etc/letsencrypt/live/malikarakh.uz/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_session_cache shared:SSL:10m;

    add_header Strict-Transport-Security "max-age=31536000" always;

    location / {
        proxy_pass http://nextjs_frontend;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

