server {
    listen 80;
    server_name api.malikarakh.uz www.api.malikarakh.uz www.malikarakh.uz malikarakh.uz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}